#! /bin/sh

### Auto start ###
sxhkd &
launchpolybar &
sh ~/.fehbg &
picom --experimental-backends &
udiskie &
dunst & 
mpd &
unclutter &
transmission-daemon & 

### Configuations ###
bspc monitor -d 1 2 3 4 

bspc config border_width         6
bspc config window_gap          12
bspc config border_radius 	12
bspc config top_padding 	18

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config single_monocle 	  true
bspc config focus_follows_pointer true
bspc config automatic_scheme 	  longest_side

### Colors ###
bspc config focused_border_color "#8FBCBB" 
bspc config normal_border_color "#222D32"
bspc config presel_feedback_color "#1ABB9B"
bspc config border_width 1

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a chromium private=on
bspc rule -a mpv state=fullscreen
bspc rule -a Galculator state=floating sticky=on rectangle=684x268+684+1
bspc rule -a Zathura state=tiled
